DROP TABLE Kocka CASCADE CONSTRAINTS;
DROP TABLE Hostitel CASCADE CONSTRAINTS;
DROP TABLE Hracka CASCADE CONSTRAINTS;
DROP TABLE Teritorium CASCADE CONSTRAINTS;
DROP TABLE Zivot CASCADE CONSTRAINTS;
DROP TABLE Kocka_Teritorium CASCADE CONSTRAINTS;

CREATE TABLE Kocka (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
    jmeno VARCHAR(50),
    rasa VARCHAR(50),

    PRIMARY KEY (ID)
);

CREATE TABLE Hostitel (
    ID INT GENERATED BY DEFAULT AS IDENTITY,
    jmeno VARCHAR(50),
    vek INT,
    pohlavi VARCHAR(50),

    rodne_cislo VARCHAR(10) UNIQUE, -- https://www.cssz.cz/web/cz/standardni-kontrola-rodneho-cisla-a-evidencniho-cisla-pojistence
    CONSTRAINT check_rc_length CHECK (REGEXP_LIKE(rodne_cislo, '^(\d{9,10})$')),
    CONSTRAINT check_rc000 CHECK ((LENGTH(rodne_cislo) != 9) OR (SUBSTR(rodne_cislo, 7, 3) != '000')),
    CONSTRAINT check_rc_mmdd CHECK (SUBSTR(rodne_cislo, 3, 2) BETWEEN '01' AND '12' AND SUBSTR(rodne_cislo, 5, 2) BETWEEN '01' AND '31'),

    cislo_bankovniho_uctu VARCHAR(21) NOT NULL UNIQUE, -- https://www.kutac.cz/pocitace-a-internety/jak-poznat-spravne-cislo-uctu
    CONSTRAINT check_bank CHECK (REGEXP_LIKE(cislo_bankovniho_uctu, '^([0-9]{6})?[0-9]{10}/[0-9]{4}$')),

    ID_kocky INT,

    PRIMARY KEY (ID),
    FOREIGN KEY (ID_kocky) REFERENCES Kocka(ID)
);

CREATE TABLE Hracka (
    ID INT GENERATED BY DEFAULT AS IDENTITY,
    typ VARCHAR(50),
    barva VARCHAR(50),
    cena DECIMAL(10,2),

    ID_hostitele INT,

    PRIMARY KEY (ID),
    FOREIGN KEY (ID_hostitele) REFERENCES Hostitel(ID)
    -- ktera kocka vlastni danou hracku lze zjistit pres hostitele, ktery ji zakonite koupil sve kocce
);

CREATE TABLE Teritorium (
    ID INT GENERATED BY DEFAULT AS IDENTITY,
    nazev VARCHAR(255),
    rozloha DECIMAL(10,2),

    PRIMARY KEY (ID)
);

CREATE TABLE Zivot (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ID_kocky INT,

    datum_narozeni DATE,
    cas_narozeni TIMESTAMP, -- v pripade instatni smrti

    delka_zivota INT NULL,
    zpusob_smrti varchar(433) NULL,
    ID_teritoria INT NULL,

    PRIMARY KEY (ID, ID_kocky),
    FOREIGN KEY (ID_kocky) REFERENCES Kocka(ID),
    FOREIGN KEY (ID_teritoria) REFERENCES Teritorium(ID)

    -- tento postup jsme zvolili jelikoz zivot ma pouze jednu specializaci a tedy po jeho zaniknuti se doplni zbyvajici informace
);

CREATE TABLE Kocka_Teritorium (
    ID_kocky INT,
    ID_teritoria INT,
    PRIMARY KEY (ID_kocky, ID_teritoria),
    FOREIGN KEY (ID_kocky) REFERENCES Kocka(ID),
    FOREIGN KEY (ID_teritoria) REFERENCES Teritorium(ID)
);

INSERT INTO Kocka (jmeno, rasa) VALUES ('Micka', 'Muu');
INSERT INTO Kocka (jmeno, rasa) VALUES ('Honzik', 'zmrdecek');
INSERT INTO Kocka (jmeno, rasa) VALUES ('DJKhaled', 'music');
INSERT INTO Kocka (jmeno, rasa) VALUES ('Dolejska', 'Dolejska');

INSERT INTO Hostitel (jmeno, vek, pohlavi, rodne_cislo, cislo_bankovniho_uctu, ID_kocky) VALUES ('Pepa', 20, 'autak', '000101111', '1234567890/0123', 1);
INSERT INTO Hostitel (jmeno, vek, pohlavi, rodne_cislo, cislo_bankovniho_uctu, ID_kocky) VALUES ('Jana', 203, 'zena', '1203306969', '3647086432/7452', 2);
INSERT INTO Hostitel (jmeno, vek, pohlavi, rodne_cislo, cislo_bankovniho_uctu, ID_kocky) VALUES ('Jirka', 21, 'vrtulnik', '1207121236', '5284957284/7654', 3);
INSERT INTO Hostitel (jmeno, vek, pohlavi, rodne_cislo, cislo_bankovniho_uctu, ID_kocky) VALUES ('Jirka', 89, 'muz', '9911111111', '5294628502/2346', 1);


